# Generated by Django 4.1.3 on 2023-06-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mushroomspot',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
