# Generated by Django 4.1.3 on 2023-07-11 11:21

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0002_mushroomspot_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', djgeojson.fields.PointField(blank=True)),
            ],
        ),
    ]
