# Generated by Django 4.1.3 on 2023-07-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0003_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
