# Generated by Django 4.1.3 on 2023-06-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nestkasten', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nestkast',
            options={'verbose_name': 'Nestkast', 'verbose_name_plural': 'Nestkasten'},
        ),
    ]
