# Generated by Django 4.1.3 on 2023-06-29 13:36

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nestkasten', '0002_alter_nestkast_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fourageergebied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
                ('geom', djgeojson.fields.PolygonField()),
            ],
        ),
        migrations.AddField(
            model_name='nestkast',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestkast',
            name='location',
            field=djgeojson.fields.PointField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestkast',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
