# Generated by Django 4.1.3 on 2023-06-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestkasten', '0005_alter_nestkast_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fourageergebied',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
