# Generated by Django 4.1.3 on 2023-06-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargestations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=250)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
